# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

services:
  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
  postgresql:
    image: postgres:11.7
    env:
      POSTGRES_USER: rails_user
      POSTGRES_PASSWORD: rails_user
    ports:
      - 3306:3306

pool:
  vmImage: 'ubuntu-latest'

variables:
  RAILS_ENV: test
  DB_HOST: localhost
  DB_USER: rails_app
  DB_PASSWORD: rails_app
  REDIS_URL: 'redis://localhost:6379/1'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '= 2.6'

- script: sudo apt-get install libpq-dev
  displayName: 'install middleware'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: yarn install
  displayName: 'yarn install'

- script: bin/rails db:create
  displayName: 'db create'
