# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

services:
  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
  postgresql:
    image: postgres:11.7
    ports:
      - 3306:3306

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '= 2.6'

- script: sudo apt-get install libpq-dev
  displayName: 'install middleware'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: yarn install
  displayName: 'yarn install'

- script: |
    apt install redis-tools
    redis-cli -h redis ping
