version: '3.9'

services:
  web:
    build:
     context: .
    secrets:
      - master_key
    image: my_rails_template:0.0.1
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
    environment:
      BUNDLE_PATH: "/app/vendor/bundle"
      BINDING: "0.0.0.0"
      RAILS_SERVE_STATIC_FILES: 1
      RAILS_LOG_TO_STDOUT: 1
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -p 3000"
    expose: ["3000"]
    ports: ["3000:3000"]
    working_dir: /app

secrets:
  master_key:
    file: config/master.key

volumes:
  bundle:
  node_modules:
