version: '3'
services:
  web: &app_base
    build:
      context: .
      dockerfile: Dockerfile
    image: railsapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: $DOCKER_RAILS_ENV
      REDIS_URL: $REDIS_URL
      WEBPACKER_DEV_SERVER_HOST: $WEBPACKER_DEV_SERVER_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
    depends_on:
      - db
      - redis
  redis:
    image: redis:6.0.8-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server
  db:
    image: postgres:11.9-alpine
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
  webpacker:
    <<: *app_base
    ports:
      - "3305:3305"
    command: bin/webpack-dev-server
volumes:
  bundle:
  db_data:
  redis_data:
  node_modules:
