version: '3'
services:
  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server
  db:
    image: postgres:11.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'rails_app'
      POSTGRES_PASSWORD: 'rails_app'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: 'redis://redis:6379/0'
    depends_on:
      - db
      - redis
volumes:
  bundle:
  db_data:
  redis_data:
