name: Create Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-for-production:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create Docker Image for Production
      run: |
        docker build -f Dockerfile.prd -t rails_for_azure_webapps:latest .

  build-for-azure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: create Docker Image for Azure
      run: |
        docker build -f Dockerfile.prd.azure -t rails_for_azure_webapps_azure:latest .
