name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAILS_ENV: test
  APP_DB_HOST: localhost
  APP_DB_PORT: 5432
  APP_DB_USERNAME: rails_app
  APP_DB_PASSWORD: rails_app
  # REDIS_URL: 'redis://localhost:6379/1'

jobs:
  test:

    runs-on: ubuntu-latest

    # add postgresql service
    # see. https://help.github.com/ja/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres:13.3-alpine
        env:
          POSTGRES_USER: 'rails_app'
          POSTGRES_PASSWORD: 'rails_app'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      # redis:
      #   image: redis:6.0-alpine
      #   options: >-
      #     --health-cmd "redis-cli ping"
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 5
      #   ports:
      #     - 6379:6379
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundler-cache: true
    - name: yarn install
      run: bin/rails yarn:install
    - name: create database
      run: bin/rails db:create
    - name: create tables
      run: bin/rails db:migrate
    - name: Run tests
      run: bundle exec rake
